= Instructions

In another terminal

 fn start

In project

 mvn clean package

 fn build

 fn deploy --app fn-duke --local

 fn invoke fn-duke fn-duke

 curl -H "Content-Type: application/json" -d "Duke" http://localhost:8080/t/fn-duke/fn-duke-trigger

== Oracle Cloud

*NOTE:* These instructions are mostly for reminding me during talks.
You will need to set up your own Oracle Cloud account and enviroment in order to be able to replicate.

=== Set up the environment

==== Fn Context
 fn use context oci-curl

==== Login to Docker
 docker login phx.ocir.io
 Username: ivar/ivar.oracle.cloud@agilejava.eu
 Password: <paste token here>

==== Configure oci-curl
 source ~/oci-curl/oci-curl.sh

=== Invoke Function
==== fn-cli
 fn invoke FunctionDuke fn-duke

==== oci-curl
 oci-curl x3vzdahhy3a.us-phoenix-1.functions.oci.oraclecloud.com GET "/t/fn-duke-trigger"

==== Java

In the fn-java-sdk-invoke project

 source env.settings
 java -jar target/fn-java-sdk-invoke-1.0-SNAPSHOT.jar FunctionCompartment FunctionDuke fn-duke